FROM alpine AS builder
WORKDIR /strangescout
RUN apk add --update nodejs nodejs-npm
COPY ./ ./
RUN sed -i s/localhost/$JSCOUT_DOMAIN/ src/environments/environment.prod.ts
RUN npm install -g @angular/cli
RUN npm update --save
RUN ng build --prod

FROM joshix/caddy:latest
COPY Caddyfile_traefik /var/www/html/Caddyfile
COPY --from=builder /strangescout/dist/jscout /srv
EXPOSE 80 443
VOLUME /.caddy/
ENTRYPOINT ["caddy", "-agree"]
