#!/bin/sh -e

domain=localhost
port=80

printf "setting default domain: $domain"
printf "setting default port: $port"

snapctl set domain=$domain
snapctl set port=$port

printf "{\n" > $SNAP_COMMON/service.conf.json
printf "\"domain\": \"%s\",\n" "$domain" >> $SNAP_COMMON/service.conf.json
printf "\"port\": \"%s\"\n" "$port" >> $SNAP_COMMON/service.conf.json
printf "}\n" >> $SNAP_COMMON/service.conf.json
